services:
  - type: web
    name: data-processing-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd app && gunicorn main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0 